requires 'File::Slurp';
requires 'JSON::MaybeXS';
requires 'LWP::Protocol::https';
requires 'LWP::UserAgent';
requires 'Term::ProgressBar';
requires 'Text::CSV';

on 'develop' => sub {
    requires 'Perl::Critic';
    requires 'Readonly';
}

